server:
  port: 20045

spring:
  datasource:
    url: jdbc:mysql://47.92.168.116:30102/jiahe
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: dehoop123
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 5
    host: 121.89.247.94
    port: 30119

  security:
    user:
      name: jiahe
      password: jiahe

  jpa:
    hibernate:
      # 自动更新
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #日志中显示sql语句
    show-sql: true

